# -*- coding: utf-8 -*-
"""Sistema_de_Auditoria_de_Recursos_Corporativos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXI9nrdfjJY3NyD_I_5MquycRKsdaWBr
"""

import time

empresa = {
    "Matriz": {
        "TI": {
            "Infraestrutura": 120000,
            "Desenvolvimento": 95000,
        },
        "RH": {
            "Recrutamento": 60000,
            "Treinamento": 35000,
        },
        "Marketing": {
            "Digital": 55000,
            "Eventos": 40000,
        },
    },
    "Filial SP": {
        "Vendas": 75000,
        "Logística": 90000,
    },
}

def auditor(funcao):
    def wrapper(*args, **kwargs):
        print("=" * 50)
        print("  AUDITORIA — INÍCIO DO CÁLCULO")
        print("=" * 50)
        print(f"  Departamentos ignorados : {args[1:]}")
        print(f"  Parâmetros de câmbio    : {kwargs}")
        inicio = time.perf_counter()
        resultado = funcao(*args, **kwargs)
        fim = time.perf_counter()
        print(f"  Tempo de execução       : {fim - inicio:.6f}s")
        print("=" * 50)
        return resultado
    return wrapper

@auditor
def calcular_orcamento(estrutura, *args, **kwargs):
    taxa = kwargs.get("taxa_cambio", 1.0)
    moeda = kwargs.get("moeda_destino", "USD")

    def somar(no):
        if isinstance(no, (int, float)):
            return no
        total = 0
        for nome, conteudo in no.items():
            if nome in args:
                print(f"  >> Ignorando: {nome}")
                continue
            total += somar(conteudo)
        return total

    total_usd = somar(estrutura)
    total_convertido = total_usd * taxa
    print(f"\n  Total (USD)  : US$ {total_usd:,.2f}")
    print(f"  Total ({moeda}) : {total_convertido:,.2f}\n")
    return total_convertido

calcular_orcamento(empresa)

calcular_orcamento(
    empresa,
    "TI", "Marketing",
    moeda_destino="BRL",
    taxa_cambio=5.20
)