# -*- coding: utf-8 -*-
"""Engenharia_de_Contexto_e_Lógica_Física.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXI9nrdfjJY3NyD_I_5MquycRKsdaWBr
"""

### PARTE 1: O Algoritmo do Microclima Local

dados_locais = [

  ["Praça Metrô Itaquera",     17, 82, 38, 27, 32, 72],

  ["Cruzamento Radial/Aricanduva", 18, 78, 65, 28, 30, 95],

  ["UNICID - Vila Carrão",     17, 80, 42, 26, 34, 58],

]



HORARIOS = ["Manhã (07h)", "Tarde (14h)"]





def classificar_iqa(iqa: int) -> str:

  """Classifica o IQAr conforme faixas oficiais CETESB/CONAMA 506/2024."""

  match True:

    case _ if iqa <= 40:

      return "✅ Boa"

    case _ if iqa <= 80:

      return "🟡 Moderada"

    case _ if iqa <= 120:

      return "🟠 Ruim"

    case _ if iqa <= 200:

      return "🔴 Muito Ruim"

    case _:

      return "⛔ Péssima"





def calcular_nota_conforto(temp: float, umid: float, iqa: int) -> float:

  """

  Fórmula própria de Nota de Conforto Urbano (0 a 10).



  Critérios:

  - Temperatura ideal: entre 18°C e 24°C.

   Penaliza proporcionalmente desvios acima ou abaixo.

  - Umidade ideal: entre 50% e 70%.

   Abaixo de 30% ou acima de 90% penaliza fortemente.

  - IQA: quanto menor, melhor. Normaliza o impacto sobre a nota.



  Fórmula:

   nota_temp = 10 - min(10, abs(temp - 21) * 0.7)

   nota_umid = 10 - min(10, abs(umid - 60) * 0.15)

   nota_iqa = 10 - min(10, iqa * 0.05)

   nota_final = (nota_temp * 0.35) + (nota_umid * 0.25) + (nota_iqa * 0.40)

  """

  nota_temp = 10 - min(10, abs(temp - 21) * 0.7)

  nota_umid = 10 - min(10, abs(umid - 60) * 0.15)

  nota_iqa = 10 - min(10, iqa * 0.05)



  nota_final = (nota_temp * 0.35) + (nota_umid * 0.25) + (nota_iqa * 0.40)

  return round(nota_final, 2)





def analisar_microclima():

  """Função principal: processa e exibe os dados climáticos do trajeto."""



  print("=" * 60)

  print(" ANÁLISE DE MICROCLIMA: Itaquera → UNICID (Vila Carrão)")

  print(" Fonte: CGE SP / CETESB / AccuWeather | Abril/2026")

  print("=" * 60)



  # Loop externo: itera sobre cada local do trajeto

  for local in dados_locais:

    nome_local = local[0]

    print(f"\n📍 LOCAL: {nome_local}")

    print("-" * 50)



    # Organiza os dados nos dois horários

    medicoes = [

      (local[1], local[2], local[3]), # manhã: temp, umid, iqa

      (local[4], local[5], local[6]), # tarde: temp, umid, iqa

    ]



    # Loop interno: itera sobre os horários e métricas do local

    for i, (temp, umid, iqa) in enumerate(medicoes):

      horario = HORARIOS[i]

      metricas = [

        ("Temperatura", f"{temp}°C"),

        ("Umidade",  f"{umid}%"),

        ("IQAr",    f"{iqa} → {classificar_iqa(iqa)}"),

      ]



      print(f"\n ⏰ {horario}")



      # Segundo loop aninhado: itera sobre cada métrica

      for nome_metrica, valor in metricas:

        print(f"  • {nome_metrica:15s}: {valor}")



      nota = calcular_nota_conforto(temp, umid, iqa)

      print(f"  ⭐ Nota de Conforto Urbano: {nota} / 10.0")



  print("\n" + "=" * 60)

  print(" Fim da análise.")

  print("=" * 60)







analisar_microclima()





### PARTE 2: Navegação e Evacuação Espacial

locais = [

  "Sala de Aula (1º Andar)",

  "Porta da Sala",

  "Corredor (virar à esquerda)",

  "Escada (descer ao térreo)",

  "Saída do Bloco C (porta corta-fogo)",

  "Área Externa – Virar à Direita (RUA)",

]



estados = [

  "livre",

  "porta_travada",

  "livre",

  "escada_estreita",

  "porta_corta_fogo",

  "saida",

]



agente = {"posicao": 0, "energia": 100, "chave": True, "historico": []}





def registrar(msg):

  agente["historico"].append(msg)

  print(f" ➤ {msg}")





def simular_evacuacao():

  print("🚨 ALARME DE INCÊNDIO! Iniciando evacuação – Bloco C / UNICID\n")



  tentativas, evacuado = 0, False



  while agente["energia"] > 0 and tentativas < 20:

    tentativas += 1

    pos, estado = agente["posicao"], estados[agente["posicao"]]



    print(f"\n[Nó {pos}] 📍 {locais[pos]} | Estado: {estado} | Energia: {agente['energia']}%")



    if estado == "saida":

      registrar("🎉 Chegou à RUA! Evacuação concluída!")

      evacuado = True

      break



    if estado == "livre":

      registrar("Caminho livre → avançando.")

      agente["posicao"] += 1

      agente["energia"] -= 5



    elif estado == "porta_travada":

      if agente["chave"]:

        registrar("Porta travada. Tem chave → destrancando e avançando.")

        agente["posicao"] += 1

        agente["energia"] -= 10

      else:

        registrar("Porta travada. SEM chave → retrocedendo.")

        agente["posicao"] = max(0, agente["posicao"] - 1)

        agente["energia"] -= 15



    elif estado == "escada_estreita":

      if agente["energia"] >= 20:

        registrar("Escada estreita. Energia ok → descendo com cuidado.")

        agente["posicao"] += 1

        agente["energia"] -= 20

      else:

        registrar("⚠️ Energia baixa na escada! Aguardando.")

        agente["energia"] -= 5



    elif estado == "porta_corta_fogo":

      if agente["energia"] >= 15:

        registrar("Porta corta-fogo → aplicando força e abrindo.")

        agente["posicao"] += 1

        agente["energia"] -= 15

      else:

        registrar("❌ Sem força para a porta corta-fogo → recuando.")

        agente["posicao"] = max(0, agente["posicao"] - 1)

        agente["energia"] -= 10



  print("\n" + "=" * 50)

  print("✅ Evacuação bem-sucedida!" if evacuado else

     "❌ Sem energia." if agente["energia"] <= 0 else

     "⏱️ Limite de tentativas atingido.")

  print(f"Tentativas: {tentativas} | Energia final: {agente['energia']}%")

  print(f"Posição final: {locais[agente['posicao']]}")

  print("\n📋 Histórico:")

  for i, acao in enumerate(agente["historico"], 1):

    print(f" {i}. {acao}")





simular_evacuacao()